services:

  postgres:
    container_name: postgres_max_hackathon
    image: postgres:17.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      TZ: Europe/Moscow
    volumes:
      - postgres_data_m
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - max_hackathon

  backend:
    container_name: backend_max_hackathon
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - ./backend/.env
    environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/hiring?schema=public
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - max_hackathon
    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:8000/health" ]
#      interval: 10s
#      timeout: 3s
#      retries: 5
#      start_period: 5s

  frontend:
    container_name: frontend_max_hackathon
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./docker/config/nginx/${NGINX_FILE}:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      TZ: Europe/Moscow
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - max_hackathon
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1/" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s


volumes:
  postgres_data_m:

networks:
  max_hackathon:
    external: true
    driver: bridge
